version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=your_database_name
            - DB_USERNAME=your_database_username
            - DB_PASSWORD=your_database_password

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: your_database_name
            MYSQL_USER: your_database_username
            MYSQL_PASSWORD: your_database_password
            MYSQL_ROOT_PASSWORD: your_root_password
        ports:
            - "3306:3306"
